-- MySQL Script generated by MySQL Workbench
-- Fri Dec 25 20:19:37 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema unrdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `unrdb` ;

-- -----------------------------------------------------
-- Schema unrdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unrdb` DEFAULT CHARACTER SET utf8 ;
USE `unrdb` ;

-- -----------------------------------------------------
-- Table `unrdb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`User` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`User` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NULL,
  `lastName` VARCHAR(255) NULL,
  `middleName` VARCHAR(255) NULL,
  `profilePic` VARCHAR(255) NULL,
  `userPwHash` VARCHAR(255) NULL,
  `userPinHash` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `userGeohash` VARCHAR(255) NULL COMMENT '			',
  `dob` DATE NULL,
  `fb_id` VARCHAR(255) NULL,
  `fb_token` TEXT(50) NULL,
  `fb_refreshtoken` TEXT(50) NULL,
  `tw_id` VARCHAR(255) NULL,
  `tw_token` TEXT(50) NULL,
  `tw_displayName` VARCHAR(255) NULL,
  `tw_username` VARCHAR(255) NULL,
  `g_id` VARCHAR(255) NULL,
  `stripe_user_id` VARCHAR(255) NULL,
  `stripe_access_token` VARCHAR(255) NULL,
  `stripe_refresh_token` VARCHAR(255) NULL,
  `stripe_publishable_key` VARCHAR(255) NULL,
  `g_token` TEXT(50) NULL,
  `g_refreshtoken` TEXT(50) NULL,
  `user_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`userID`),
  INDEX `userGeoHash` (`userGeohash` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fb_id` (`fb_id` ASC),
  INDEX `tw_id` (`tw_id` ASC),
  INDEX `g_id` (`g_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`UserSchedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`UserSchedule` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`UserSchedule` (
  `userScheduleID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_UserSchedule_userID` INT UNSIGNED NOT NULL,
  `shiftStart` TINYINT(2) UNSIGNED NOT NULL,
  `shiftDuration` TINYINT(2) UNSIGNED NOT NULL,
  `dayOfWeek` TINYINT(1) UNSIGNED NOT NULL,
  `minimumPayPerHour` DECIMAL(10,2) UNSIGNED NOT NULL,
  INDEX `fk_UserSchedule_userID_idx` (`fk_UserSchedule_userID` ASC),
  PRIMARY KEY (`userScheduleID`, `fk_UserSchedule_userID`),
  CONSTRAINT `fk_UserSchedule_userID`
    FOREIGN KEY (`fk_UserSchedule_userID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`UserLicense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`UserLicense` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`UserLicense` (
  `userLicenseID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_UserLicense_userID` INT UNSIGNED NOT NULL,
  `licenseNumber` VARCHAR(255) NOT NULL,
  `licenseState` VARCHAR(255) NOT NULL,
  `licensePhotoUrl` VARCHAR(255) NULL,
  `expiration` DATE NOT NULL,
  `licenseVetted` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  `createdDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX `licensePhotoUrl_UNIQUE` (`licensePhotoUrl` ASC),
  INDEX `fk_UserLicense_userID_idx` (`fk_UserLicense_userID` ASC),
  PRIMARY KEY (`userLicenseID`, `fk_UserLicense_userID`, `licenseNumber`, `licenseState`),
  CONSTRAINT `fk_UserLicense_userID`
    FOREIGN KEY (`fk_UserLicense_userID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`Facility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`Facility` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`Facility` (
  `facilityID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `facilityEmail` VARCHAR(255) NOT NULL,
  `facilityName` VARCHAR(255) NULL,
  `facilityGeohash` VARCHAR(255) NULL,
  `facilityPwHash` VARCHAR(255) NOT NULL,
  `facilityEMR` VARCHAR(255) NULL,
  `facilityVetted` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`facilityID`),
  INDEX `facilityGeohash` (`facilityGeohash` ASC),
  UNIQUE INDEX `facilityName` (`facilityName` ASC),
  INDEX `facilityEmail` (`facilityEmail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`UserWorkHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`UserWorkHistory` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`UserWorkHistory` (
  `userHistoryID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_UserWorkHistory_userID` INT UNSIGNED NOT NULL,
  `fk_UserWorkHistory_facilityID` INT UNSIGNED NOT NULL,
  `months` SMALLINT(4) UNSIGNED NOT NULL,
  `referenceName` VARCHAR(255) NOT NULL,
  `referencePhone` VARCHAR(255) NOT NULL,
  `workHistoryVetted` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  INDEX `fk_UserWorkHistory_userID_idx` (`fk_UserWorkHistory_userID` ASC),
  INDEX `fk_UserWorkHistory_facilityID_idx` (`fk_UserWorkHistory_facilityID` ASC),
  PRIMARY KEY (`userHistoryID`, `fk_UserWorkHistory_userID`, `fk_UserWorkHistory_facilityID`),
  CONSTRAINT `fk_UserWorkHistory_userID`
    FOREIGN KEY (`fk_UserWorkHistory_userID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UserWorkHistory_facilityID`
    FOREIGN KEY (`fk_UserWorkHistory_facilityID`)
    REFERENCES `unrdb`.`Facility` (`facilityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`Email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`Email` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`Email` (
  `emailID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emailAddress` VARCHAR(255) NOT NULL,
  `emailType` VARCHAR(255) NULL,
  PRIMARY KEY (`emailID`),
  UNIQUE INDEX `emailAddress_UNIQUE` (`emailAddress` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`UserEmail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`UserEmail` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`UserEmail` (
  `fk_UserEmail_userID` INT UNSIGNED NOT NULL,
  `fk_UserEmail_emailID` INT UNSIGNED NOT NULL,
  INDEX `fk_UserEmail_userID_idx` (`fk_UserEmail_userID` ASC),
  INDEX `fk_UserEmail_emailID_idx` (`fk_UserEmail_emailID` ASC),
  PRIMARY KEY (`fk_UserEmail_userID`, `fk_UserEmail_emailID`),
  CONSTRAINT `fk_UserEmail_userID`
    FOREIGN KEY (`fk_UserEmail_userID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UserEmail_emailID`
    FOREIGN KEY (`fk_UserEmail_emailID`)
    REFERENCES `unrdb`.`Email` (`emailID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`Phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`Phone` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`Phone` (
  `phoneID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phoneNumber` VARCHAR(255) NOT NULL,
  `ext` VARCHAR(255) NULL,
  `phoneType` VARCHAR(255) NULL,
  PRIMARY KEY (`phoneID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`Address` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`Address` (
  `addressID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `address2` VARCHAR(255) NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `zip` VARCHAR(255) NOT NULL,
  `geohash` VARCHAR(255) NULL,
  PRIMARY KEY (`addressID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`UserPhone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`UserPhone` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`UserPhone` (
  `fk_UserPhone_userID` INT UNSIGNED NOT NULL,
  `fk_UserPhone_phoneID` INT UNSIGNED NOT NULL,
  INDEX `fk_UserPhone_userID_idx` (`fk_UserPhone_userID` ASC),
  INDEX `fk_UserPhone_phoneID_idx` (`fk_UserPhone_phoneID` ASC),
  PRIMARY KEY (`fk_UserPhone_userID`, `fk_UserPhone_phoneID`),
  CONSTRAINT `fk_UserPhone_phoneID`
    FOREIGN KEY (`fk_UserPhone_phoneID`)
    REFERENCES `unrdb`.`Phone` (`phoneID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UserPhone_userID`
    FOREIGN KEY (`fk_UserPhone_userID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`UserAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`UserAddress` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`UserAddress` (
  `fk_UserAddress_userID` INT UNSIGNED NOT NULL,
  `fk_UserAddress_addressID` INT UNSIGNED NOT NULL,
  INDEX `fk_UserAddress_addressID_idx` (`fk_UserAddress_addressID` ASC),
  INDEX `fk_UserAddress_userID_idx` (`fk_UserAddress_userID` ASC),
  PRIMARY KEY (`fk_UserAddress_userID`, `fk_UserAddress_addressID`),
  CONSTRAINT `fk_UserAddress_userID`
    FOREIGN KEY (`fk_UserAddress_userID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UserAddress_addressID`
    FOREIGN KEY (`fk_UserAddress_addressID`)
    REFERENCES `unrdb`.`Address` (`addressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`Specialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`Specialty` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`Specialty` (
  `specialtyID` SMALLINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
  `specialty` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`specialtyID`),
  UNIQUE INDEX `specialty_UNIQUE` (`specialty` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`Shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`Shift` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`Shift` (
  `shiftID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `open` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `accepted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `pending` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `completed` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `fk_Shift_facilityID` INT UNSIGNED NOT NULL,
  `fk_Shift_specialtyID` SMALLINT(4) UNSIGNED NOT NULL,
  `fk_Shift_userID` INT UNSIGNED NULL,
  `shiftStartHour` TINYINT(2) UNSIGNED NOT NULL,
  `shiftDuration` TINYINT(2) UNSIGNED NOT NULL,
  `payPerHour` DECIMAL(10,2) UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `shift_posted` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `shift_modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `facilityPaid` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `userPaid` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `shiftDressCode` VARCHAR(255) NOT NULL DEFAULT 'sterile scrubs',
  `stripeToken` VARCHAR(255) NULL,
  `cents` INT UNSIGNED NOT NULL DEFAULT 0,
  INDEX `fk_Shift_specialtyID_idx` (`fk_Shift_specialtyID` ASC),
  INDEX `fk_Shift_facilityID_idx` (`fk_Shift_facilityID` ASC),
  INDEX `fk_Shift_userID_idx` (`fk_Shift_userID` ASC),
  PRIMARY KEY (`shiftID`),
  INDEX `open` (`open` ASC),
  CONSTRAINT `fk_Shift_specialtyID`
    FOREIGN KEY (`fk_Shift_specialtyID`)
    REFERENCES `unrdb`.`Specialty` (`specialtyID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Shift_facilityID`
    FOREIGN KEY (`fk_Shift_facilityID`)
    REFERENCES `unrdb`.`Facility` (`facilityID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Shift_userID`
    FOREIGN KEY (`fk_Shift_userID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`ShiftComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`ShiftComment` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`ShiftComment` (
  `commentID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fk_ShiftComment_shiftID` BIGINT(20) UNSIGNED NOT NULL,
  `fk_ShiftComment_authorID` INT UNSIGNED NOT NULL,
  `comment` VARCHAR(140) NOT NULL,
  `comment_posted` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `comment_modified` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_ShiftComment_shiftID_idx` (`fk_ShiftComment_shiftID` ASC),
  INDEX `fk_ShiftComment_authorID_idx` (`fk_ShiftComment_authorID` ASC),
  PRIMARY KEY (`commentID`, `fk_ShiftComment_shiftID`, `fk_ShiftComment_authorID`),
  CONSTRAINT `fk_ShiftComment_shiftID`
    FOREIGN KEY (`fk_ShiftComment_shiftID`)
    REFERENCES `unrdb`.`Shift` (`shiftID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ShiftComment_authorID`
    FOREIGN KEY (`fk_ShiftComment_authorID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`ShiftCommentTree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`ShiftCommentTree` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`ShiftCommentTree` (
  `fk_ShiftCommentTree_parent` BIGINT(20) UNSIGNED NOT NULL,
  `fk_ShiftCommentTree_child` BIGINT(20) UNSIGNED NOT NULL,
  `path_length` TINYINT(2) UNSIGNED NOT NULL,
  INDEX `fk_ShiftCommentTree_child_idx` (`fk_ShiftCommentTree_child` ASC),
  INDEX `fk_ShiftCommentTree_parent_idx` (`fk_ShiftCommentTree_parent` ASC),
  PRIMARY KEY (`fk_ShiftCommentTree_parent`, `fk_ShiftCommentTree_child`),
  CONSTRAINT `fk_ShiftCommentTree_parent`
    FOREIGN KEY (`fk_ShiftCommentTree_parent`)
    REFERENCES `unrdb`.`ShiftComment` (`commentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ShiftCommentTree_child`
    FOREIGN KEY (`fk_ShiftCommentTree_child`)
    REFERENCES `unrdb`.`ShiftComment` (`commentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`UserSpecialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`UserSpecialty` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`UserSpecialty` (
  `fk_UserSpecialty_userID` INT UNSIGNED NOT NULL,
  `fk_UserSpecialty_specialtyID` SMALLINT(4) UNSIGNED NOT NULL,
  `yearsOfExp` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  INDEX `fk_UserSpecialty_userID_idx` (`fk_UserSpecialty_userID` ASC),
  INDEX `fk_UserSpecialty_specialtyID_idx` (`fk_UserSpecialty_specialtyID` ASC),
  PRIMARY KEY (`fk_UserSpecialty_userID`, `fk_UserSpecialty_specialtyID`),
  CONSTRAINT `fk_UserSpecialty_userID`
    FOREIGN KEY (`fk_UserSpecialty_userID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UserSpecialty_specialtyID`
    FOREIGN KEY (`fk_UserSpecialty_specialtyID`)
    REFERENCES `unrdb`.`Specialty` (`specialtyID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`FacilityUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`FacilityUser` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`FacilityUser` (
  `fk_FacilityUser_facilityID` INT UNSIGNED NOT NULL,
  `fk_FacilityUser_userID` INT UNSIGNED NOT NULL,
  INDEX `fk_FacilityUsers_facilityID_idx` (`fk_FacilityUser_facilityID` ASC),
  INDEX `fk_FacilityUsers_userID_idx` (`fk_FacilityUser_userID` ASC),
  PRIMARY KEY (`fk_FacilityUser_facilityID`, `fk_FacilityUser_userID`),
  CONSTRAINT `fk_FacilityUsers_facilityID`
    FOREIGN KEY (`fk_FacilityUser_facilityID`)
    REFERENCES `unrdb`.`Facility` (`facilityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FacilityUsers_userID`
    FOREIGN KEY (`fk_FacilityUser_userID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`FacilityEmail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`FacilityEmail` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`FacilityEmail` (
  `fk_FacilityEmail_facilityID` INT UNSIGNED NOT NULL,
  `fk_FacilityEmail_emailID` INT UNSIGNED NOT NULL,
  INDEX `fk_FacilityEmail_facilityID_idx` (`fk_FacilityEmail_facilityID` ASC),
  INDEX `fk_FacilityEmail_emailID_idx` (`fk_FacilityEmail_emailID` ASC),
  PRIMARY KEY (`fk_FacilityEmail_facilityID`, `fk_FacilityEmail_emailID`),
  CONSTRAINT `fk_FacilityEmail_facilityID`
    FOREIGN KEY (`fk_FacilityEmail_facilityID`)
    REFERENCES `unrdb`.`Facility` (`facilityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FacilityEmail_emailID`
    FOREIGN KEY (`fk_FacilityEmail_emailID`)
    REFERENCES `unrdb`.`Email` (`emailID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`FacilityPhone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`FacilityPhone` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`FacilityPhone` (
  `fk_FacilityPhone_facilityID` INT UNSIGNED NOT NULL,
  `fk_FacilityPhone_phoneID` INT UNSIGNED NOT NULL,
  INDEX `fk_FacilityPhone_phoneID_idx` (`fk_FacilityPhone_phoneID` ASC),
  INDEX `fk_FacilityPhone_facilityID_idx` (`fk_FacilityPhone_facilityID` ASC),
  PRIMARY KEY (`fk_FacilityPhone_facilityID`, `fk_FacilityPhone_phoneID`),
  CONSTRAINT `fk_FacilityPhone_facilityID`
    FOREIGN KEY (`fk_FacilityPhone_facilityID`)
    REFERENCES `unrdb`.`Facility` (`facilityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FacilityPhone_phoneID`
    FOREIGN KEY (`fk_FacilityPhone_phoneID`)
    REFERENCES `unrdb`.`Phone` (`phoneID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`FacilityAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`FacilityAddress` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`FacilityAddress` (
  `fk_FacilityAddress_facilityID` INT UNSIGNED NOT NULL,
  `fk_FacilityAddress_addressID` INT UNSIGNED NOT NULL,
  INDEX `fk_FacilityAddress_addressID_idx` (`fk_FacilityAddress_addressID` ASC),
  INDEX `fk_FacilityAddress_facilityID_idx` (`fk_FacilityAddress_facilityID` ASC),
  PRIMARY KEY (`fk_FacilityAddress_facilityID`, `fk_FacilityAddress_addressID`),
  CONSTRAINT `fk_FacilityAddress_facilityID`
    FOREIGN KEY (`fk_FacilityAddress_facilityID`)
    REFERENCES `unrdb`.`Facility` (`facilityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FacilityAddress_addressID`
    FOREIGN KEY (`fk_FacilityAddress_addressID`)
    REFERENCES `unrdb`.`Address` (`addressID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`ShiftReviewOnFacility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`ShiftReviewOnFacility` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`ShiftReviewOnFacility` (
  `fk_ShiftReviewOnFacility_facilityID` INT UNSIGNED NOT NULL,
  `fk_ShiftReviewOnFacility_shiftID` BIGINT(20) UNSIGNED NOT NULL,
  `review` TINYINT(1) UNSIGNED NOT NULL,
  INDEX `fk_ShiftReviewOnFacility_shiftID_idx` (`fk_ShiftReviewOnFacility_shiftID` ASC),
  INDEX `fk_ShiftReviewOnFacility_facilityID_idx` (`fk_ShiftReviewOnFacility_facilityID` ASC),
  PRIMARY KEY (`fk_ShiftReviewOnFacility_facilityID`, `fk_ShiftReviewOnFacility_shiftID`),
  CONSTRAINT `fk_ShiftReviewOnFacility_facilityID`
    FOREIGN KEY (`fk_ShiftReviewOnFacility_facilityID`)
    REFERENCES `unrdb`.`Facility` (`facilityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ShiftReviewOnFacility_shiftID`
    FOREIGN KEY (`fk_ShiftReviewOnFacility_shiftID`)
    REFERENCES `unrdb`.`Shift` (`shiftID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`ShiftReviewOnUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`ShiftReviewOnUser` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`ShiftReviewOnUser` (
  `fk_ShiftReviewOnUser_userID` INT UNSIGNED NOT NULL,
  `fk_ShiftReviewOnUser_shiftID` BIGINT(20) UNSIGNED NOT NULL,
  `review` TINYINT(1) UNSIGNED NOT NULL,
  INDEX `fk_ ShiftReviewsOnUser_shiftID_idx` (`fk_ShiftReviewOnUser_shiftID` ASC),
  INDEX `fk_ ShiftReviewsOnUser_userID_idx` (`fk_ShiftReviewOnUser_userID` ASC),
  PRIMARY KEY (`fk_ShiftReviewOnUser_userID`, `fk_ShiftReviewOnUser_shiftID`),
  CONSTRAINT `fk_ ShiftReviewsOnUser_userID`
    FOREIGN KEY (`fk_ShiftReviewOnUser_userID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ ShiftReviewsOnUser_shiftID`
    FOREIGN KEY (`fk_ShiftReviewOnUser_shiftID`)
    REFERENCES `unrdb`.`Shift` (`shiftID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`ShiftViewed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`ShiftViewed` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`ShiftViewed` (
  `fk_ShiftViewed_shiftID` BIGINT(20) UNSIGNED NOT NULL,
  `fk_ShiftViewed_userID` INT UNSIGNED NOT NULL,
  `shiftViewed_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_ShiftViewed_shiftID` (`fk_ShiftViewed_shiftID` ASC),
  INDEX `fk_ShiftViewed_userID` (`fk_ShiftViewed_userID` ASC),
  PRIMARY KEY (`fk_ShiftViewed_shiftID`, `fk_ShiftViewed_userID`),
  CONSTRAINT `fk_ViewedShift_shiftID`
    FOREIGN KEY (`fk_ShiftViewed_shiftID`)
    REFERENCES `unrdb`.`Shift` (`shiftID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ViewedShift_userID`
    FOREIGN KEY (`fk_ShiftViewed_userID`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`UserReferral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`UserReferral` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`UserReferral` (
  `parent` INT UNSIGNED NOT NULL,
  `child` INT UNSIGNED NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`parent`),
  UNIQUE INDEX `child_UNIQUE` (`child` ASC),
  CONSTRAINT `parent`
    FOREIGN KEY (`parent`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `child`
    FOREIGN KEY (`child`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`FacilityReferral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`FacilityReferral` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`FacilityReferral` (
  `parent` INT UNSIGNED NOT NULL,
  `child` INT UNSIGNED NOT NULL,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`parent`),
  UNIQUE INDEX `child_UNIQUE` (`child` ASC),
  CONSTRAINT `parentUser`
    FOREIGN KEY (`parent`)
    REFERENCES `unrdb`.`User` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `childFacility`
    FOREIGN KEY (`child`)
    REFERENCES `unrdb`.`Facility` (`facilityID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`BetaUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`BetaUser` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`BetaUser` (
  `email` VARCHAR(255) NOT NULL,
  `signedUp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unrdb`.`Geohash`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `unrdb`.`Geohash` ;

CREATE TABLE IF NOT EXISTS `unrdb`.`Geohash` (
  `address` VARCHAR(255) NOT NULL,
  `lat` DECIMAL(10,8) NOT NULL COMMENT '			',
  `lng` DECIMAL(11,8) NOT NULL,
  PRIMARY KEY (`address`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
