-- MySQL Script generated by MySQL Workbench
-- Wed Jul 22 15:52:01 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema UNRdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `UNRdb` ;

-- -----------------------------------------------------
-- Schema UNRdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UNRdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `UNRdb` ;

-- -----------------------------------------------------
-- Table `UNRdb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`User` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`User` (
  `userID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `firstName` VARCHAR(45) NOT NULL COMMENT '',
  `lastName` VARCHAR(45) NOT NULL COMMENT '',
  `middleName` VARCHAR(45) NULL COMMENT '',
  `passwordHash` VARCHAR(45) NOT NULL COMMENT '',
  `userName` VARCHAR(45) NOT NULL COMMENT '',
  `geohash` BIGINT(20) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`userID`)  COMMENT '',
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC)  COMMENT '',
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC)  COMMENT '',
  INDEX `geohash` (`geohash` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`UserSchedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`UserSchedule` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`UserSchedule` (
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  `shiftStart` TINYINT(2) UNSIGNED NOT NULL COMMENT '',
  `shiftDuration` TINYINT(2) UNSIGNED NOT NULL COMMENT '',
  `dayOfWeek` TINYINT(1) UNSIGNED NOT NULL COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`UserLicense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`UserLicense` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`UserLicense` (
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  `licenseNumber` VARCHAR(45) NOT NULL COMMENT '',
  `licenseState` VARCHAR(45) NULL COMMENT '',
  `licenseCountry` VARCHAR(45) NULL COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  UNIQUE INDEX `licenseNumber_UNIQUE` (`licenseNumber` ASC)  COMMENT '',
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`UserWorkHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`UserWorkHistory` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`UserWorkHistory` (
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  `facilityID` BIGINT(20) NOT NULL COMMENT '',
  `duration` TINYINT(4) NOT NULL COMMENT '',
  `referenceName` VARCHAR(45) NULL COMMENT '',
  `referencePhone` VARCHAR(45) NULL COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `UNRdb`.`Email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`Email` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`Email` (
  `emailID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `emailAddress` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`emailID`)  COMMENT '',
  UNIQUE INDEX `emailID_UNIQUE` (`emailID` ASC)  COMMENT '',
  UNIQUE INDEX `emailAddress_UNIQUE` (`emailAddress` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`UserEmail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`UserEmail` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`UserEmail` (
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  `emailID` INT UNSIGNED NOT NULL COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`emailID` ASC)  COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emailID`
    FOREIGN KEY (`emailID`)
    REFERENCES `UNRdb`.`Email` (`emailID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`Phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`Phone` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`Phone` (
  `phoneID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `phoneNumber` INT NOT NULL COMMENT '',
  `ext` INT NULL COMMENT '',
  `phoneType` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`phoneID`)  COMMENT '',
  UNIQUE INDEX `phoneID_UNIQUE` (`phoneID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`Address` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`Address` (
  `addressID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `adress` VARCHAR(45) NOT NULL COMMENT '',
  `address2` VARCHAR(45) NULL COMMENT '',
  `city` VARCHAR(20) NOT NULL COMMENT '',
  `state` VARCHAR(20) NOT NULL COMMENT '',
  `zip` INT NOT NULL COMMENT '',
  PRIMARY KEY (`addressID`)  COMMENT '',
  UNIQUE INDEX `addressID_UNIQUE` (`addressID` ASC)  COMMENT '')
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `UNRdb`.`UserPhone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`UserPhone` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`UserPhone` (
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  `phoneID` INT UNSIGNED NOT NULL COMMENT '',
  UNIQUE INDEX `phoneID_UNIQUE` (`phoneID` ASC)  COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  CONSTRAINT `phoneID`
    FOREIGN KEY (`phoneID`)
    REFERENCES `UNRdb`.`Phone` (`phoneID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`UserAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`UserAddress` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`UserAddress` (
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  `addressID` INT UNSIGNED NOT NULL COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  INDEX `addressID_idx` (`addressID` ASC)  COMMENT '',
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `addressID`
    FOREIGN KEY (`addressID`)
    REFERENCES `UNRdb`.`Address` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`Facility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`Facility` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`Facility` (
  `facilityID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `facilityName` VARCHAR(45) NULL COMMENT '',
  `geohash` BIGINT(20) NULL COMMENT '',
  `passwordHash` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`facilityID`)  COMMENT '',
  UNIQUE INDEX `facilityID_UNIQUE` (`facilityID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`CompletedShift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`CompletedShift` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`CompletedShift` (
  `shiftID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  `facilityID` INT UNSIGNED NOT NULL COMMENT '',
  `shiftHour` TINYINT(2) UNSIGNED NOT NULL COMMENT '',
  `dateTime` DATETIME NOT NULL COMMENT '',
  INDEX `facilityID_idx` (`facilityID` ASC)  COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  PRIMARY KEY (`shiftID`)  COMMENT '',
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `facilityID`
    FOREIGN KEY (`facilityID`)
    REFERENCES `UNRdb`.`Facility` (`facilityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`Comment` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`Comment` (
  `shiftID` BIGINT(20) UNSIGNED NOT NULL COMMENT '',
  `to` INT UNSIGNED NOT NULL COMMENT '',
  `comment` VARCHAR(140) NOT NULL COMMENT '',
  INDEX `shiftID_idx` (`shiftID` ASC)  COMMENT '',
  CONSTRAINT `shiftID`
    FOREIGN KEY (`shiftID`)
    REFERENCES `UNRdb`.`CompletedShift` (`shiftID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`Rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`Rating` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`Rating` (
  `shiftID` BIGINT(20) UNSIGNED NOT NULL COMMENT '',
  `rating` TINYINT(1) UNSIGNED NOT NULL COMMENT '',
  INDEX `shiftID_idx` (`shiftID` ASC)  COMMENT '',
  CONSTRAINT `shiftID`
    FOREIGN KEY (`shiftID`)
    REFERENCES `UNRdb`.`CompletedShift` (`shiftID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`CommentTree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`CommentTree` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`CommentTree` (
  `parent` BIGINT(20) UNSIGNED NOT NULL COMMENT '',
  `child` BIGINT(20) UNSIGNED NOT NULL COMMENT '',
  INDEX `parent_idx` (`parent` ASC)  COMMENT '',
  INDEX `child_idx` (`child` ASC)  COMMENT '',
  CONSTRAINT `parent`
    FOREIGN KEY (`parent`)
    REFERENCES `UNRdb`.`Comment` (`shiftID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `child`
    FOREIGN KEY (`child`)
    REFERENCES `UNRdb`.`Comment` (`shiftID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`UserComment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`UserComment` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`UserComment` (
  `userID` BIGINT(20) UNSIGNED NOT NULL COMMENT '',
  `commentID` BIGINT(20) UNSIGNED NOT NULL COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  INDEX `commentID_idx` (`commentID` ASC)  COMMENT '',
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `commentID`
    FOREIGN KEY (`commentID`)
    REFERENCES `UNRdb`.`Comment` (`shiftID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`Specialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`Specialty` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`Specialty` (
  `specialtyID` SMALLINT(4) UNSIGNED NOT NULL COMMENT '',
  `specialty` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`specialtyID`)  COMMENT '',
  UNIQUE INDEX `specialtyID_UNIQUE` (`specialtyID` ASC)  COMMENT '',
  UNIQUE INDEX `specialty_UNIQUE` (`specialty` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`UserSpecialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`UserSpecialty` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`UserSpecialty` (
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  `specialtyID` SMALLINT(4) UNSIGNED NOT NULL COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  INDEX `specialtyID_idx` (`specialtyID` ASC)  COMMENT '',
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `specialtyID`
    FOREIGN KEY (`specialtyID`)
    REFERENCES `UNRdb`.`Specialty` (`specialtyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`PendingShifts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`PendingShifts` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`PendingShifts` (
  `shiftID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  `facilityID` INT UNSIGNED NOT NULL COMMENT '',
  `shiftHour` TINYINT(2) UNSIGNED NOT NULL COMMENT '',
  `dateTime` DATETIME NOT NULL COMMENT '',
  INDEX `facilityID_idx` (`facilityID` ASC)  COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  PRIMARY KEY (`shiftID`)  COMMENT '',
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `facilityID`
    FOREIGN KEY (`facilityID`)
    REFERENCES `UNRdb`.`Facility` (`facilityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`OpenShifts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`OpenShifts` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`OpenShifts` (
  `shiftID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  `facilitID` INT UNSIGNED NOT NULL COMMENT '',
  `shiftHour` TINYINT(2) UNSIGNED NOT NULL COMMENT '',
  `dateTime` DATETIME NOT NULL COMMENT '',
  INDEX `facilityID_idx` (`facilitID` ASC)  COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  PRIMARY KEY (`shiftID`)  COMMENT '',
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `facilityID`
    FOREIGN KEY (`facilitID`)
    REFERENCES `UNRdb`.`Facility` (`facilityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`FacilityUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`FacilityUsers` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`FacilityUsers` (
  `facilityID` INT UNSIGNED NOT NULL COMMENT '',
  `userID` INT UNSIGNED NOT NULL COMMENT '',
  INDEX `facilityID_idx` (`facilityID` ASC)  COMMENT '',
  INDEX `userID_idx` (`userID` ASC)  COMMENT '',
  CONSTRAINT `facilityID`
    FOREIGN KEY (`facilityID`)
    REFERENCES `UNRdb`.`Facility` (`facilityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `UNRdb`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`FacilityEmail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`FacilityEmail` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`FacilityEmail` (
  `facilityID` INT UNSIGNED NOT NULL COMMENT '',
  `emailID` INT UNSIGNED NOT NULL COMMENT '',
  INDEX `facilityID_idx` (`facilityID` ASC)  COMMENT '',
  INDEX `emailID_idx` (`emailID` ASC)  COMMENT '',
  CONSTRAINT `facilityID`
    FOREIGN KEY (`facilityID`)
    REFERENCES `UNRdb`.`Facility` (`facilityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emailID`
    FOREIGN KEY (`emailID`)
    REFERENCES `UNRdb`.`Email` (`emailID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`FacilityPhone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`FacilityPhone` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`FacilityPhone` (
  `facilityID` INT UNSIGNED NOT NULL COMMENT '',
  `phoneID` INT UNSIGNED NOT NULL COMMENT '',
  INDEX `phoneID_idx` (`phoneID` ASC)  COMMENT '',
  INDEX `facilityID_idx` (`facilityID` ASC)  COMMENT '',
  CONSTRAINT `facilityID`
    FOREIGN KEY (`facilityID`)
    REFERENCES `UNRdb`.`Facility` (`facilityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `phoneID`
    FOREIGN KEY (`phoneID`)
    REFERENCES `UNRdb`.`Phone` (`phoneID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`FacilityAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`FacilityAddress` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`FacilityAddress` (
  `facilityID` INT UNSIGNED NOT NULL COMMENT '',
  `addressID` INT UNSIGNED NOT NULL COMMENT '',
  INDEX `addressID_idx` (`addressID` ASC)  COMMENT '',
  INDEX `facilityID_idx` (`facilityID` ASC)  COMMENT '',
  CONSTRAINT `facilityID`
    FOREIGN KEY (`facilityID`)
    REFERENCES `UNRdb`.`Facility` (`facilityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `addressID`
    FOREIGN KEY (`addressID`)
    REFERENCES `UNRdb`.`Address` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`Shift`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`Shift` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`Shift` (
  `shiftID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `shiftHours` TINYINT(2) UNSIGNED NOT NULL COMMENT '',
  `shiftDay` DATETIME NOT NULL COMMENT '',
  UNIQUE INDEX `shiftID_UNIQUE` (`shiftID` ASC)  COMMENT '',
  PRIMARY KEY (`shiftID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UNRdb`.`ShiftDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UNRdb`.`ShiftDetails` ;

CREATE TABLE IF NOT EXISTS `UNRdb`.`ShiftDetails` (
  `shiftHours` TINYINT(2) UNSIGNED NOT NULL COMMENT '',
  `shiftType` VARCHAR(45) NOT NULL COMMENT '',
  UNIQUE INDEX `shiftType_UNIQUE` (`shiftType` ASC)  COMMENT '',
  UNIQUE INDEX `shiftHours_UNIQUE` (`shiftHours` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
