'use strict';

export default {
  LOAD: 'LOAD',
  CLEAR: 'CLEAR',
  SORTBYDISTANCEASC: 'SORTBYDISTANCEASC',
  SORTBYDISTANCEDEC: 'SORTBYDISTANCEDEC',
  SORTBYPRICEASC: 'SORTBYPRICEASC',
  SORTBYPRICEDEC: 'SORTBYPRICEDEC',
};
